name: Update Sun Calendar

on:
  # Esegue l'azione ogni 3 giorni alle 00:00 UTC
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set remote URL with GITHUB_TOKEN
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/selirof/sun-calendar.git"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # <--- Fissato a 3.10 per evitare rotture

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          pip install ics # Rimuoviamo il blocco delle versioni per ics e tatsu

      - name: Generate ICS file
        run: |
          python create_calendar_local.py

      - name: Commit and push changes
        run: |
          git add sun.ics
          git commit -m "Update sun.ics [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
          git push origin HEAD:main
